### ISSUE TITLE
Find a solution to transfer the database/tables easily (git)

### ISSUE THREAD

**Issue by dnmx9133** [Alihanoa/Diem-explorer#5]

**Comment by Alihanoa** [comment]
There is a major problem with this issue and i have found two alternatives to it. 

The first one is using Github as "server" in which we do not store data. Rather we would store whats called "DML" files. These files would have SQL scripts to reassemble the data on our  localmachines. As time goes by our database is going to be quite huge and reassembling all that data is gonna take some time. So i don't know if this is a valid strategy.

Another valid alternative is to find a free database hosting plattform in which the data is stored and each data generating would store the data immediately on the right server under the right conditions. Since we do not have images/videos, the size of the data shouldn't increase by multiple megabytes.

And well the last alternative would be to find a valid datahosting platform which won't be free :).
